"""Curated Nifty 500 stock list (top ~200 by market cap for fast scanning)."""

NIFTY_500 = [
    # Nifty 50 (Top large caps)
    ("RELIANCE", "Reliance Industries", "Oil & Gas"),
    ("TCS", "Tata Consultancy Services", "IT"),
    ("HDFCBANK", "HDFC Bank", "Banking"),
    ("BHARTIARTL", "Bharti Airtel", "Telecom"),
    ("ICICIBANK", "ICICI Bank", "Banking"),
    ("INFY", "Infosys", "IT"),
    ("SBIN", "State Bank of India", "Banking"),
    ("HINDUNILVR", "Hindustan Unilever", "FMCG"),
    ("ITC", "ITC Limited", "FMCG"),
    ("LT", "Larsen & Toubro", "Construction"),
    ("BAJFINANCE", "Bajaj Finance", "NBFC"),
    ("KOTAKBANK", "Kotak Mahindra Bank", "Banking"),
    ("HCLTECH", "HCL Technologies", "IT"),
    ("MARUTI", "Maruti Suzuki", "Auto"),
    ("SUNPHARMA", "Sun Pharma", "Pharma"),
    ("AXISBANK", "Axis Bank", "Banking"),
    ("M&M", "Mahindra & Mahindra", "Auto"),
    ("NTPC", "NTPC Limited", "Power"),
    ("TITAN", "Titan Company", "Consumer Durables"),
    ("ULTRACEMCO", "UltraTech Cement", "Cement"),
    ("BAJAJFINSV", "Bajaj Finserv", "Financial Services"),
    ("ONGC", "Oil & Natural Gas Corp", "Oil & Gas"),
    ("ADANIENT", "Adani Enterprises", "Diversified"),
    ("POWERGRID", "Power Grid Corp", "Power"),
    ("TATAMOTORS", "Tata Motors", "Auto"),
    ("WIPRO", "Wipro", "IT"),
    ("NESTLEIND", "Nestle India", "FMCG"),
    ("JSWSTEEL", "JSW Steel", "Metals"),
    ("ADANIPORTS", "Adani Ports", "Infrastructure"),
    ("COALINDIA", "Coal India", "Mining"),
    ("HINDALCO", "Hindalco Industries", "Metals"),
    ("ASIANPAINT", "Asian Paints", "Paints"),
    ("BAJAJ-AUTO", "Bajaj Auto", "Auto"),
    ("TATASTEEL", "Tata Steel", "Metals"),
    ("GRASIM", "Grasim Industries", "Cement"),
    ("TECHM", "Tech Mahindra", "IT"),
    ("DRREDDY", "Dr Reddy's Labs", "Pharma"),
    ("CIPLA", "Cipla", "Pharma"),
    ("INDUSINDBK", "IndusInd Bank", "Banking"),
    ("EICHERMOT", "Eicher Motors", "Auto"),
    ("BEL", "Bharat Electronics", "Defence"),
    ("BRITANNIA", "Britannia Industries", "FMCG"),
    ("APOLLOHOSP", "Apollo Hospitals", "Healthcare"),
    ("HEROMOTOCO", "Hero MotoCorp", "Auto"),
    ("HDFCLIFE", "HDFC Life Insurance", "Insurance"),
    ("SBILIFE", "SBI Life Insurance", "Insurance"),
    ("SHRIRAMFIN", "Shriram Finance", "NBFC"),
    ("TATACONSUM", "Tata Consumer Products", "FMCG"),
    ("DIVISLAB", "Divis Laboratories", "Pharma"),
    ("TRENT", "Trent Limited", "Retail"),

    # Next 50 large/mid caps
    ("DMART", "Avenue Supermarts", "Retail"),
    ("PIDILITIND", "Pidilite Industries", "Chemicals"),
    ("HAVELLS", "Havells India", "Consumer Durables"),
    ("DABUR", "Dabur India", "FMCG"),
    ("GODREJCP", "Godrej Consumer", "FMCG"),
    ("MARICO", "Marico", "FMCG"),
    ("SIEMENS", "Siemens", "Capital Goods"),
    ("ABB", "ABB India", "Capital Goods"),
    ("BOSCHLTD", "Bosch", "Auto Ancillary"),
    ("ADANIGREEN", "Adani Green Energy", "Power"),
    ("ADANIPOWER", "Adani Power", "Power"),
    ("TATAPOWER", "Tata Power", "Power"),
    ("VEDL", "Vedanta", "Metals"),
    ("SAIL", "Steel Authority", "Metals"),
    ("NMDC", "NMDC", "Mining"),
    ("GAIL", "GAIL India", "Oil & Gas"),
    ("IOC", "Indian Oil Corp", "Oil & Gas"),
    ("BPCL", "Bharat Petroleum", "Oil & Gas"),
    ("HINDPETRO", "HPCL", "Oil & Gas"),
    ("PFC", "Power Finance Corp", "NBFC"),
    ("RECLTD", "REC Limited", "NBFC"),
    ("IRFC", "Indian Railway Finance", "NBFC"),
    ("CHOLAFIN", "Cholamandalam Investment", "NBFC"),
    ("MUTHOOTFIN", "Muthoot Finance", "NBFC"),
    ("BAJAJHLDNG", "Bajaj Holdings", "Financial Services"),
    ("ICICIPRULI", "ICICI Prudential", "Insurance"),
    ("ICICIGI", "ICICI Lombard", "Insurance"),
    ("LICHSGFIN", "LIC Housing Finance", "NBFC"),
    ("PNBHOUSING", "PNB Housing Finance", "NBFC"),
    ("BANKBARODA", "Bank of Baroda", "Banking"),
    ("PNB", "Punjab National Bank", "Banking"),
    ("CANBK", "Canara Bank", "Banking"),
    ("UNIONBANK", "Union Bank", "Banking"),
    ("IDFCFIRSTB", "IDFC First Bank", "Banking"),
    ("FEDERALBNK", "Federal Bank", "Banking"),
    ("AUBANK", "AU Small Finance Bank", "Banking"),
    ("BANDHANBNK", "Bandhan Bank", "Banking"),
    ("YESBANK", "Yes Bank", "Banking"),
    ("RBLBANK", "RBL Bank", "Banking"),
    ("LODHA", "Macrotech Developers", "Realty"),
    ("DLF", "DLF Limited", "Realty"),
    ("GODREJPROP", "Godrej Properties", "Realty"),
    ("OBEROIRLTY", "Oberoi Realty", "Realty"),
    ("PRESTIGE", "Prestige Estates", "Realty"),
    ("PHOENIXLTD", "Phoenix Mills", "Realty"),
    ("BRIGADE", "Brigade Enterprises", "Realty"),

    # IT
    ("LTIM", "LTIMindtree", "IT"),
    ("PERSISTENT", "Persistent Systems", "IT"),
    ("COFORGE", "Coforge", "IT"),
    ("MPHASIS", "Mphasis", "IT"),
    ("LTTS", "L&T Technology Services", "IT"),
    ("OFSS", "Oracle Financial", "IT"),
    ("KPITTECH", "KPIT Technologies", "IT"),
    ("TATATECH", "Tata Technologies", "IT"),

    # Pharma
    ("ZYDUSLIFE", "Zydus Lifesciences", "Pharma"),
    ("LUPIN", "Lupin", "Pharma"),
    ("AUROPHARMA", "Aurobindo Pharma", "Pharma"),
    ("TORNTPHARM", "Torrent Pharma", "Pharma"),
    ("ALKEM", "Alkem Laboratories", "Pharma"),
    ("BIOCON", "Biocon", "Pharma"),
    ("GLENMARK", "Glenmark Pharma", "Pharma"),
    ("IPCALAB", "Ipca Labs", "Pharma"),
    ("ABBOTINDIA", "Abbott India", "Pharma"),
    ("MANKIND", "Mankind Pharma", "Pharma"),
    ("MAXHEALTH", "Max Healthcare", "Healthcare"),
    ("FORTIS", "Fortis Healthcare", "Healthcare"),
    ("SYNGENE", "Syngene International", "Pharma"),
    ("LAURUSLABS", "Laurus Labs", "Pharma"),

    # Auto & Ancillaries
    ("TVSMOTOR", "TVS Motor", "Auto"),
    ("ASHOKLEY", "Ashok Leyland", "Auto"),
    ("MRF", "MRF", "Auto Ancillary"),
    ("BALKRISIND", "Balkrishna Industries", "Auto Ancillary"),
    ("APOLLOTYRE", "Apollo Tyres", "Auto Ancillary"),
    ("MOTHERSON", "Samvardhana Motherson", "Auto Ancillary"),
    ("BHARATFORG", "Bharat Forge", "Auto Ancillary"),
    ("EXIDEIND", "Exide Industries", "Auto Ancillary"),
    ("TIINDIA", "Tube Investments", "Auto Ancillary"),

    # Metals & Mining
    ("JINDALSTEL", "Jindal Steel", "Metals"),
    ("NATIONALUM", "National Aluminium", "Metals"),
    ("JSL", "Jindal Stainless", "Metals"),

    # Consumer / Retail
    ("VBL", "Varun Beverages", "FMCG"),
    ("COLPAL", "Colgate Palmolive", "FMCG"),
    ("UBL", "United Breweries", "FMCG"),
    ("MCDOWELL-N", "United Spirits", "FMCG"),
    ("PGHH", "Procter & Gamble H&H", "FMCG"),
    ("JUBLFOOD", "Jubilant FoodWorks", "FMCG"),
    ("PAGEIND", "Page Industries", "Textiles"),
    ("RELAXO", "Relaxo Footwears", "Consumer"),
    ("BATA", "Bata India", "Consumer"),
    ("NYKAA", "FSN E-Commerce", "Retail"),
    ("ZOMATO", "Zomato", "Retail"),
    ("SWIGGY", "Swiggy", "Retail"),
    ("PAYTM", "One 97 Communications", "Fintech"),
    ("POLICYBZR", "PB Fintech", "Fintech"),

    # Capital Goods / Engineering
    ("CUMMINSIND", "Cummins India", "Capital Goods"),
    ("THERMAX", "Thermax", "Capital Goods"),
    ("BHEL", "BHEL", "Capital Goods"),
    ("SUZLON", "Suzlon Energy", "Power"),
    ("INOXWIND", "Inox Wind", "Power"),
    ("HAL", "Hindustan Aeronautics", "Defence"),
    ("BEML", "BEML", "Defence"),
    ("MAZDOCK", "Mazagon Dock", "Defence"),
    ("COCHINSHIP", "Cochin Shipyard", "Defence"),
    ("SOLARINDS", "Solar Industries", "Defence"),
    ("APARINDS", "Apar Industries", "Capital Goods"),
    ("CGPOWER", "CG Power", "Capital Goods"),
    ("POLYCAB", "Polycab India", "Capital Goods"),
    ("KEI", "KEI Industries", "Capital Goods"),
    ("VOLTAS", "Voltas", "Consumer Durables"),
    ("BLUESTARCO", "Blue Star", "Consumer Durables"),
    ("CROMPTON", "Crompton Greaves Consumer", "Consumer Durables"),

    # Cement
    ("SHREECEM", "Shree Cement", "Cement"),
    ("AMBUJACEM", "Ambuja Cements", "Cement"),
    ("ACC", "ACC", "Cement"),
    ("DALBHARAT", "Dalmia Bharat", "Cement"),
    ("JKCEMENT", "JK Cement", "Cement"),
    ("RAMCOCEM", "Ramco Cements", "Cement"),

    # Chemicals & Fertilizers
    ("SRF", "SRF Limited", "Chemicals"),
    ("PIIND", "PI Industries", "Chemicals"),
    ("UPL", "UPL Limited", "Chemicals"),
    ("DEEPAKNTR", "Deepak Nitrite", "Chemicals"),
    ("AARTIIND", "Aarti Industries", "Chemicals"),
    ("NAVINFLUOR", "Navin Fluorine", "Chemicals"),
    ("ATUL", "Atul Limited", "Chemicals"),
    ("TATACHEM", "Tata Chemicals", "Chemicals"),
    ("COROMANDEL", "Coromandel International", "Fertilizers"),
    ("CHAMBLFERT", "Chambal Fertilizers", "Fertilizers"),

    # Textiles
    ("KPRMILL", "K.P.R. Mill", "Textiles"),
    ("VARDHACRLC", "Vardhman Textiles", "Textiles"),

    # Telecom & Media
    ("IDEA", "Vodafone Idea", "Telecom"),
    ("INDUSTOWER", "Indus Towers", "Telecom"),
    ("ZEEL", "Zee Entertainment", "Media"),
    ("PVRINOX", "PVR Inox", "Media"),

    # Others
    ("IRCTC", "IRCTC", "Services"),
    ("CONCOR", "Container Corp", "Services"),
    ("BLUEDART", "Blue Dart Express", "Logistics"),
    ("DELHIVERY", "Delhivery", "Logistics"),
    ("INTERGLOBE", "InterGlobe Aviation", "Aviation"),
    ("SPICEJET", "SpiceJet", "Aviation"),
    ("ADANITRANS", "Adani Energy Solutions", "Power"),
    ("JIOFIN", "Jio Financial", "Financial Services"),
    ("LICI", "LIC of India", "Insurance"),
    ("IREDA", "IREDA", "NBFC"),
    ("RVNL", "Rail Vikas Nigam", "Infrastructure"),
    ("IRCON", "IRCON International", "Infrastructure"),
    ("NHPC", "NHPC", "Power"),
    ("SJVN", "SJVN", "Power"),
    ("GMRAIRPORT", "GMR Airports", "Aviation"),
    ("ASTRAL", "Astral Limited", "Pipes"),
    ("SUPREMEIND", "Supreme Industries", "Plastics"),
    ("BERGEPAINT", "Berger Paints", "Paints"),
    ("KANSAINER", "Kansai Nerolac", "Paints"),
    ("INDIANB", "Indian Bank", "Banking"),
    ("CENTRALBK", "Central Bank of India", "Banking"),
    ("IOB", "Indian Overseas Bank", "Banking"),
    ("UCOBANK", "UCO Bank", "Banking"),
    ("MAHABANK", "Bank of Maharashtra", "Banking"),
    ("KARURVYSYA", "Karur Vysya Bank", "Banking"),
    ("SOUTHBANK", "South Indian Bank", "Banking"),
    ("MANAPPURAM", "Manappuram Finance", "NBFC"),
    ("SUNDARMFIN", "Sundaram Finance", "NBFC"),
    ("M&MFIN", "M&M Financial", "NBFC"),
    ("PEL", "Piramal Enterprises", "NBFC"),
    ("SBICARD", "SBI Cards", "NBFC"),
    ("HUDCO", "HUDCO", "NBFC"),
    ("STARHEALTH", "Star Health Insurance", "Insurance"),
    ("GICRE", "GIC Re", "Insurance"),
    ("NIACL", "New India Assurance", "Insurance"),
    ("MFSL", "Max Financial", "Insurance"),
]

# Get symbol list for yfinance (append .NS suffix)
def get_yf_symbols():
    return [f"{s[0]}.NS" for s in NIFTY_500]

def get_symbol_map():
    return {f"{s[0]}.NS": {"symbol": s[0], "name": s[1], "sector": s[2]} for s in NIFTY_500}
